package cola.machine.dao;

import cola.machine.bean.PerRes;

public interface PerResMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_res
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_res
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insert(PerRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_res
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insertSelective(PerRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_res
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    PerRes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_res
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKeySelective(PerRes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_per_res
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKey(PerRes record);
}