package cola.machine.dao;

import java.util.List;


import cola.machine.bean.RolePer;

public interface RolePerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    int insert(RolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    int insertSelective(RolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    RolePer selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    int updateByPrimaryKeySelective(RolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    int updateByPrimaryKey(RolePer record);

    /**
     * 说明:根据角色id获取对应关系
     * @param id
     * @return
     * @return List<RolePer>
     * @author dozen.zhang
     * @date 2015年12月18日下午10:34:02
     */
    List<RolePer> selectByRoleId(String id);
    
    

    /**
     * 根据角色id删除 permission对应关系
     * @param id 参数
     * @author dozen.zhang
     */
    void deleteByRoleId(String id);
}