package cola.machine.dao;

import cola.machine.bean.RolePer;

public interface RolePerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insert(RolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insertSelective(RolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    RolePer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKeySelective(RolePer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role_per
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKey(RolePer record);
}