package cola.machine.dao;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import cola.machine.bean.Role;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    Role selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKey(Role record);

    /**
     * 说明:
     * @param map
     * @return
     * @return List<Role>
     * @author dozen.zhang
     * @date 2015年12月18日下午3:42:59
     */
    List<Role> selectByPage(HashMap map);

    /**
     * 说明:根据名字查询数量
     * @param name
     * @return
     * @return int
     * @author dozen.zhang
     * @date 2015年12月18日下午7:33:08
     */
    int countByName(String name);

    /**
     * 说明:
     * @param userId
     * @return
     * @return List<Role>
     * @author dozen.zhang
     * @date 2015年12月18日下午11:24:47
     */
    List<Role> selectAllByUserId(Long userId);
    
    /**
     * 分页数据
     * @param map 参数
     * @return List
     * @author dozen.zhang
     */
    List<Role> list4Page(HashMap map);

    /**
     * 返回当前用户拥有的角色列表
     * @param userId 参数
     * @return List
     * @author dozen.zhang
     * 2015年10月28日 
     * 下午6:42:54
     */
    List<Role> selectByUserId(String userId);

    /**
     * 根据用户id和用户角色查询
     * @param map 参数
     * @return int
     * @author dozen.zhang
     */
    int countByUserIdAndRoleId(Map<String, Object> map);

    /**
     * 返回所有角色列表，当前用户拥有的角色disable值为0
     * @param userId 参数
     * @return List
     * @author dozen.zhang
     * 2015年10月28日 
     * 下午6:42:34
     */
    List<Role> selectAllByUserId(String userId);

    /**
     * 获取所有角色
     * @return List
     * @author dozen.zhang
     */
    List<Role> selectAllRole();
    
    

    /**
     * @param userId 参数
     * @return List
     * @author dozen.zhang
     */
    List<Role> selectRoleListByUserid(String userId);
}