package cola.machine.dao;

import java.util.List;

import cola.machine.bean.UserRole;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    UserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_role
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    int updateByPrimaryKey(UserRole record);

    /**
     * 根据角色id 删除关联关系
     * @param id 参数
     * @author dozen.zhang
     */
    void deleteByRoleId(String id);

    /**
     * 根据用户id删除角色用户对应关系
     * @param id 参数
     * @author dozen.zhang
     */
    void deleteByUserId(String id);

    /**
     * 根据角色id 查询绑定的用户个数
     * 
     * @param id 参数
     * @return int
     */
    int countByRoleid(String id);


    /**
     * 根据用户id获取用户角色对应关系
     * @param id 参数
     * @return List
     * @author dozen.zhang
     */
    List<UserRole> selectByUserId(String id);
}