package cola.machine.bean;

public class PerRes {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_res.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_res.perId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String perId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_per_res.resId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String resId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_res.id
     *
     * @return the value of t_per_res.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_res.id
     *
     * @param id the value for t_per_res.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_res.perId
     *
     * @return the value of t_per_res.perId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_res.perId
     *
     * @param perId the value for t_per_res.perId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setPerId(String perId) {
        this.perId = perId == null ? null : perId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_per_res.resId
     *
     * @return the value of t_per_res.resId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getResId() {
        return resId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_per_res.resId
     *
     * @param resId the value for t_per_res.resId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setResId(String resId) {
        this.resId = resId == null ? null : resId.trim();
    }
}