package cola.machine.bean;

public class RolePer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_per.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_per.roleId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_per.perId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private Integer perId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_per.id
     *
     * @return the value of t_role_per.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_per.id
     *
     * @param id the value for t_role_per.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_per.roleId
     *
     * @return the value of t_role_per.roleId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_per.roleId
     *
     * @param roleId the value for t_role_per.roleId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_per.perId
     *
     * @return the value of t_role_per.perId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_per.perId
     *
     * @param perId the value for t_role_per.perId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }
}