package cola.machine.bean;

public class RolePer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_per.id
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_per.roleId
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role_per.perId
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    private String perId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_per.id
     *
     * @return the value of t_role_per.id
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_per.id
     *
     * @param id the value for t_role_per.id
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_per.roleId
     *
     * @return the value of t_role_per.roleId
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_per.roleId
     *
     * @param roleId the value for t_role_per.roleId
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role_per.perId
     *
     * @return the value of t_role_per.perId
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    public String getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role_per.perId
     *
     * @param perId the value for t_role_per.perId
     *
     * @mbggenerated Fri Dec 18 22:22:41 CST 2015
     */
    public void setPerId(String perId) {
        this.perId = perId == null ? null : perId.trim();
    }
}