package cola.machine.bean;

public class UserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.userId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user_role.roleId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    private String roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.id
     *
     * @return the value of t_user_role.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.id
     *
     * @param id the value for t_user_role.id
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.userId
     *
     * @return the value of t_user_role.userId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.userId
     *
     * @param userId the value for t_user_role.userId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user_role.roleId
     *
     * @return the value of t_user_role.roleId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user_role.roleId
     *
     * @param roleId the value for t_user_role.roleId
     *
     * @mbggenerated Sat Dec 12 10:26:59 CST 2015
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }
}